{% set name = "iriclib" %}
{% set version = "3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/i-RIC/{{ name }}
  git_rev: a6a110f117e9a6b1584289621426917a2cfdf487
  patches:
    - filetype.patch
    - unix-find-library.patch
    - macosx-rpath.patch
    - propagate-libraries.patch

build:
  number: 2

requirements:
  build:
    - cmake=2.8
    - {{ compiler('cxx') }}
    - cgns=3.2.1
  run:
    - cgns=3.2.1

about:
  home: http://i-ric.org
  license:
  summary:
    iRIC software is a free numerical simulation platform supporting a
    wide variety of computational solvers for problems in water
    science and engineering.
  dev_url: https://github.com/i-RIC/iriclib
