{% set name = "iriclib" %}
{% set version = "0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/i-RIC/{{ name }}
  git_rev: v{{ version }}
  patches:
    - filetype.patch
    - unix-find-library.patch
    - macosx-rpath.patch
    - propagate-libraries.patch
    - macos-clang.patch

build:
  number: 1

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - cgns==3.2.1=2
  run:
    - cgns==3.2.1=2

about:
  home: http://i-ric.org
  license:
  summary:
    iRIC software is a free numerical simulation platform supporting a
    wide variety of computational solvers for problems in water
    science and engineering.
  dev_url: https://github.com/i-RIC/iriclib
